### ISSUE TITLE
请问红米2(2014812)是否可以刷 LineageOS 呢？

### ISSUE THREAD

**Issue by shaobin0604** [redmi2-flashing-tips/redmi2-flashing-tips.github.io#1]
如题，谢谢！

**Comment by snailwind** [comment]
有啊第一个就是    不过停更了 
机型代码wt88047

**Comment by Flyfish233** [comment]
官方版不再支持。只有第三方。
`https://drive.google.com/file/d/1o64wFTuCrpKLKQ1tjnC96IWeQGf6Eu2L/view?usp=drivesdk`

**Comment by shaobin0604** [comment]
@Flyfish233 好的，谢谢

**Comment by Flyfish233** [comment]
> @Flyfish233 好的，谢谢

我去，这都 2020 年了，我都记不清有回复过了...我现在红米2都炸了...
